name: Build, Release, and Update Homebrew

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for all targets
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Install FFmpeg
      run: |
        brew install ffmpeg

    - name: Build for all targets
      run: |
        zig build -Drelease -Dci=true

    - name: Prepare release assets
      run: |
        mkdir release_assets
        cd zig-out
        for dir in */; do
          target=${dir%/}
          tar cvzf ../release_assets/asciigen-$target.tar.gz $target
          (cd ../release_assets && sha256sum asciigen-$target.tar.gz > asciigen-$target.tar.gz.sha256)
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: release_assets/*

  release:
    name: Create Release and Update Homebrew
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-assets
        path: release_assets

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release_assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

