name: Zig Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # arm
          - os: macos-latest
            arch: aarch64
          - os: macos-13
            arch: x86_64
          # x86
          - os: ubuntu-latest
            arch: x86_64
          - os: windows-latest
            arch: x86_64

    steps:
    - uses: actions/checkout@v4
    - uses: AnimMouse/setup-ffmpeg@v1

    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0


    - name: Build and Test
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          zig build -Drelease -Dtarget=${{ matrix.arch }}-windows test
        elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          zig build -Drelease -Dtarget=${{ matrix.arch }}-linux test
        elif [[ "${{ matrix.os }}" == macos* ]]; then
          zig build -Drelease -Dtarget=${{ matrix.arch }}-macos test
        fi
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test_output-${{ matrix.os }}-${{ matrix.arch }}
        path: test_output/
